name: 'Build'

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: "Build:dockerimage"
        uses: docker/build-push-action@v2
        with:
          tags: |
            emberquill/uranium_patcher:latest
            ghcr.io/emberquill/uranium_patcher:latest
          push: ${{ github.ref == 'refs/heads/master' }}
