name: 'Build'

on:
  push:
    branches:
      - master

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: "Build:dockerimage"
        uses: docker/build-push-action@v2
        with:
          push: "true"
          tags: uranium_patcher:latest
